### ISSUE TITLE
why? Hydraulic matrix ill-conditioned at node b

### ISSUE THREAD

**Issue by imksc** [OpenWaterAnalytics/epanet-dev#17]
Hydraulic matrix ill-conditioned at node b
  Network is numerically ill-conditioned. Simulation halted.
**\* SYSTEM ERROR 110: HYDRAULIC SOLVER FAILURE

runed and error Hydraulic matrix ill-conditioned at node b..
reservoir pattern  remove and rund ok.

[TITLE]

[JUNCTIONS]
;ID                 Elev            Demand          Pattern  
 a                  10.18           0                               ;
 b                  11.87           9789.16                         ;
 c                  11.87           0                               ;

[RESERVOIRS]
;ID                 Head            Pattern  
 r                  1               pat             ;

[PIPES]
;ID                 Node1               Node2               Length          Diameter        Roughness       MinorLoss       Status
 p2                 b                   c                   0.1             700             110             0               CLOSED;
 p1                 a                   b                   9.95388         700             120             0               OPEN  ;
 p3                 r                   c                   0.001           5000            110             0               OPEN  ;

[PUMPS]
;ID                 Node1               Node2               Parameters

[PATTERNS]
;ID                 Multipliers
 pat                0.97705225      0.977448513     0.973353796     0.977184338     0.977712688     0.977712688 
 pat                0.975203023     0.974146322     0.974938848     0.974938848     0.973882147     0.970579956 
 pat                0.974146322     0.976655987     0.975467199     0.974674673     0.970976219     0.975203023 
 pat                0.977184338     0.973750059     0.976127637     0.974674673     0.975335111     0.975599286 

[CURVES]
;ID                 X-Value         Y-Value

[COORDINATES]
;Node     X-Coord      Y-Coord
b               300378.74       178316.6  
a               300372.5        178312.05  
c               300379.7584     178315.2425 
r               300383.65       178311.16   

[REACTIONS]
Order Bulk              1
Order Tank              1
Order Wall              1
Global Bulk             0
Global Wall             0
Limiting Potential      0
Roughness Correlation   0

[OPTIONS]
FLOW_UNITS      CMD
HEADLOSS_MODEL      H-W
SPECIFIC_VISCOSITY      1
SPECIFIC_DIFFUSIVITY        1
SPECIFIC_GRAVITY        1
MAXIMUM_TRIALS      40
RELATIVE_ACCURACY       0.001
IF_UNBALANCED       CONTINUE
DEMAND_PATTERN      1
DEMAND_MULTIPLIER       1
EMITTER_EXPONENT        0.5
QUALITY_TOLERANCE       0.01
DEMAND_MODEL        FIXED
LEAKAGE_MODEL       NONE
HYDRAULIC_SOLVER        GGA
MATRIX_SOLVER       SPARSPAK
QUALITY_MODEL       NONE
QUALITY_UNITS       MG/L

[TIMES]
Duration            24:00
Hydraulic Timestep      1
Quality Timestep    0:05
Pattern Timestep        1
Pattern Start       0:00
Report Timestep     1
Report Start        0:00
Start ClockTime     12:00 AM
Statistic           NONE

[REPORT]
Status              Yes
Summary             No
Page                   0

[END]

**Comment by LRossman** [comment]
There are several bugs in the current commit that I have fixed on my local copy of the code. Your example ran successfully with my local version. I will try to get the updated version committed sometime today.

Please continue to test the code. It is very helpful to the development process. Also, as a reminder, if you want to see results tabulated in the report file you have to add a NODES and/or LINKS command in the [REPORT] section. We are thinking about posting a lightweight GUI sometime soon to make testing easier.

**Comment by imksc** [comment]
i am download.. and appled..
and before network is success..

but.. this networks is "  Hydraulic matrix ill-conditioned at node b"

also
datamanager.cpp
int DataManager::getLinkValue(int index, int param, double\* value, Network\* nw)
if ( index < 0 || index >= nw->count(Element::NODE) ) return 205; 
-> if ( index < 0 || index >= nw->count(Element::LINK) ) return 205;

[TITLE]

[JUNCTIONS]
;ID                 Elev            Demand          Pattern  
 a                  7.46            0                               ;
 b                  4.63            0                               ;
 c                  4.57            0                               ;
 d                  5.07            0                               ;
 e                  34.12           0                               ;
 f                  34.55           0                               ;

[RESERVOIRS]
;ID                 Head            Pattern  
 r                  1                               ;

[TANKS]
;ID                 Elevation       InitLevel   MinLevel        MaxLevel        Diameter        MinVol          VolCurve

[PIPES]
;ID                 Node1               Node2               Length          Diameter        Roughness       MinorLoss       Status
 p4                 b                   d                   0.26309         450             85              0               OPEN  ;
 p3                 c                   d                   3.35564         450             85              0               OPEN  ;
 p6                 b                   a                   506.90673       450             85              0               OPEN  ;
 p5                 a                   c                   495.61686       450             85              0               OPEN  ;
 p1                 r                   f                   75.0131         5000            100             0               OPEN  ;
 p2                 e                   d                   1148.83271      450             85              0               CLOSED;

[PUMPS]
;ID                 Node1               Node2               Parameters

[VALVES]
;ID                 Node1               Node2               Diameter        Type    Setting         MinorLoss 
 v1                 e                   f                   300                 FCV                 4896                0               ;

[DEMANDS]
;Junction           Demand          Pattern             Category

[QUALITY]
;Node               InitQual

[SOURCES]
;Node               Type            Quality         Pattern

[PATTERNS]
;ID                 Multipliers

[CURVES]
;ID                 X-Value         Y-Value

[COORDINATES]
;Node     X-Coord      Y-Coord
e               290662.7101     148371.3832 
r               290668.0275     148357.5954 
f               290665.4668     148366.0068 
a               290658.3344     148394.1379 
d               290663.3051     148377.7449 
b               290657.8035     148382.2917 
c               290664.3176     148381.1052 

[VERTICES]
;Linke     X-Coord      Y-Coord

[LABELS]
;X-Coord           Y-Coord          Label & Anchor Node

[REACTIONS]
;Type       Pipe/Tank           Coefficient

[REACTIONS]
Order Bulk              1
Order Tank              1
Order Wall              1
Global Bulk             0
Global Wall             0
Limiting Potential      0
Roughness Correlation   0

[LEAKAGE]
;Pipe ID        Leakage Coefficient1        Leakage Coefficient2
[STATUS]

[CONTROLS]

[RULES]

[OPTIONS]
FLOW_UNITS      CMD
HEADLOSS_MODEL      H-W
SPECIFIC_VISCOSITY      1
SPECIFIC_DIFFUSIVITY        1
SPECIFIC_GRAVITY        1
MAXIMUM_TRIALS      40
RELATIVE_ACCURACY       0.001
IF_UNBALANCED       CONTINUE
DEMAND_PATTERN      1
DEMAND_MULTIPLIER       1
EMITTER_EXPONENT        0.5
QUALITY_TOLERANCE       0.01
DEMAND_MODEL        FIXED
LEAKAGE_MODEL       NONE
HYDRAULIC_SOLVER        GGA
MATRIX_SOLVER       SPARSPAK
QUALITY_MODEL       NONE
QUALITY_UNITS       MG/L

[TIMES]
Duration            24:00
Hydraulic Timestep      1
Quality Timestep    0:05
Pattern Timestep        1
Pattern Start       0:00
Report Timestep     0:01
Report Start        0:00
Start ClockTime     12:00 AM
Statistic           NONE

[ENERGY]
Global Efficiency   75
Global Price        0
Demand Charge       0

[EMITTERS]
;Junction    Coefficient    [Exponent]    [Pattern]

[MIXING]
;Tank               Model

[REPORT]
Status              Yes
Summary             No
Page                   0

[BACKDROP]
DIMENSIONS      270228.80           132876.29           341528.82           191374.88
UNITS           None
FILE
OFFSET          0.00                0.00

[END]

**Comment by LRossman** [comment]
First, thank you for finding the bug in `getLinkValue`.
The second network you submitted runs OK on my local copy of the code. I will try to commit the latest changes today.

**Comment by imksc** [comment]
now network is no error..
thanks
