### ISSUE TITLE
emmiter result of epanet2 and epanet3 is different.

### ISSUE THREAD

**Issue by imksc** [OpenWaterAnalytics/epanet-dev#22]
i am test epanet net1.inp
junction 13 flowcoeff is 9.2.
epanet2 emmiter flow is 100.
but epanet3 emmiter flow is 150.

[TITLE]
EPANET Example Network 1
A simple example of modeling chlorine decay. Both bulk and
wall reactions are included.

[JUNCTIONS]
;ID                 Elev            Demand          Pattern  
 10                 710             0                               ;
 11                 710             150                             ;
 12                 700             150                             ;
 13                 695             100                             ;
 21                 700             150                             ;
 22                 695             200                             ;
 23                 690             150                             ;
 31                 700             100                             ;
 32                 710             100                             ;

[RESERVOIRS]
;ID                 Head            Pattern  
 9                  800                             ;

[TANKS]
;ID                 Elevation       InitLevel   MinLevel        MaxLevel        Diameter        MinVol          VolCurve
 2                  850             120             100             150             50.5            0                           ;

[PIPES]
;ID                 Node1               Node2               Length          Diameter        Roughness       MinorLoss       Status
 112                12                  22                  5280            12              100             0               OPEN  ;
 113                13                  23                  5280            8               100             0               OPEN  ;
 21                 21                  22                  5280            10              100             0               OPEN  ;
 122                22                  32                  5280            6               100             0               OPEN  ;
 121                21                  31                  5280            8               100             0               OPEN  ;
 22                 22                  23                  5280            12              100             0               OPEN  ;
 10                 10                  11                  10530           18              100             0               OPEN  ;
 31                 31                  32                  5280            6               100             0               OPEN  ;
 12                 12                  13                  5280            10              100             0               OPEN  ;
 111                11                  21                  5280            10              100             0               OPEN  ;
 110                2                   12                  200             18              100             0               OPEN  ;
 11                 11                  12                  5280            14              100             0               OPEN  ;

[PUMPS]
;ID                 Node1               Node2               Parameters
 9                  9                   10                      HEAD 1         ;

[VALVES]
;ID                 Node1               Node2               Diameter        Type    Setting         MinorLoss 

[DEMANDS]
;Junction           Demand          Pattern             Category

[QUALITY]
;Node               InitQual
23              0.5  
21              0.5  
32              0.5  
2               1.0  
22              0.5  
10              0.5  
13              0.5  
12              0.5  
31              0.5  
9               1.0  
11              0.5         

[SOURCES]
;Node               Type            Quality         Pattern

[PATTERNS]
;ID                 Multipliers
 1                  1               1.2             1.4             1.6             1.4             1.2  
 1                  1               0.8             0.6             0.4             0.6             0.8         

[CURVES]
;ID                 X-Value         Y-Value
 1                  1500                250             

[COORDINATES]
;Node     X-Coord      Y-Coord
23              70              40  
21              30              40  
32              50              10  
2               50              90  
22              50              40  
10              20              70  
13              70              70  
12              50              70  
31              30              10  
9               10              70  
11              30              70          

[VERTICES]
;Linke     X-Coord      Y-Coord

[LABELS]
;X-Coord           Y-Coord          Label & Anchor Node
6.99            73.63           "Source"  
13.48           68.13           "Pump"  
43.85           91.21           "Tank"      

[REACTIONS]
;Type       Pipe/Tank           Coefficient

[REACTIONS]
ORDER BULK              1
ORDER TANK              1
ORDER WALL              1
GLOBAL BULK             -.5
GLOBAL WALL             -1
LIMITING POTENTIAL      0.0
ROUGHNESS CORRELATION   0.0

[LEAKAGE]
;Pipe ID        Leakage Coefficient1        Leakage Coefficient2
[STATUS]

[CONTROLS]
LINK 9 OPEN IF NODE 2 BELOW 110
LINK 9 CLOSED IF NODE 2 ABOVE 140

[RULES]

[OPTIONS]
FLOW_UNITS      GPM
HEADLOSS_MODEL      H-W
SPECIFIC_VISCOSITY      1.0
SPECIFIC_DIFFUSIVITY        1.0
SPECIFIC_GRAVITY        1.0
MAXIMUM_TRIALS      40
RELATIVE_ACCURACY       0.001
IF_UNBALANCED       CONTINUE
DEMAND_PATTERN      1
DEMAND_MULTIPLIER       1.0
EMITTER_EXPONENT        0.5
QUALITY_TOLERANCE       0.01
DEMAND_MODEL        FIXED
LEAKAGE_MODEL       NONE
HYDRAULIC_SOLVER        GGA
MATRIX_SOLVER       SPARSPAK
QUALITY_MODEL       CHLORINE
QUALITY_UNITS       MG/L

[TIMES]
DURATION                24:00
HYDRAULIC TIMESTEP      1:00
QUALITY TIMESTEP        0:05
PATTERN TIMESTEP        2:00
PATTERN START           0:00
REPORT TIMESTEP         1:00
REPORT START            0:00
START CLOCKTIME         12 am
STATISTIC               None

[ENERGY]
Global Efficiency   75
Global Price        0.0
Demand Charge       0.0

[EMITTERS]
;Junction    Coefficient    [Exponent]    [Pattern]
 13                 9.2                         

[MIXING]
;Tank               Model

[REPORT]
Status              Yes
Summary             No
Page                0

[BACKDROP]
DIMENSIONS      7.00                6.00                73.00               94.00
UNITS           None
FILE
OFFSET          0.00                0.00

[TAGS]
[END]

**Comment by samhatchett** [comment]
Thanks. Do you know if either flow is theoretically correct?

**Comment by LRossman** [comment]
The EPANET 2 flow is correct. If you take the EPANET 3 solution pressure at the emitter node (at hour 0 for example) and evaluate the emitter flow by hand you get a value close to 100 gpm and not the 150 gpm that the program reports. EPANET 3 changed the way that emitters are modeled, treating them as a power pressure-dependent demand function with no upper bound. I'm hoping that this is either a simple units conversion or reporting bug. I will check it out and find a fix.

**Comment by imksc** [comment]
i download new version.. and test
now  same emiter flow.
thanks.

**Comment by imksc** [comment]
LEAKAGE_MODEL       POWER
pipe id 113  
LEAKAGE_COEFF1  = 9.136
LEAKAGE_COEFF2 = 0.5  
runed
leakage is 782.82 at hour 0.
i thank whether leakage is big.

i test emmiter 
junction id 13  flow coeff 9.136 exponent 0.5 
outflow is 99.13 at hour 0.
junction id 23  flow coeff 9.136 exponent 0.5 
outflow is 100.01 at hour 0

[TITLE]
EPANET Example Network 1
A simple example of modeling chlorine decay. Both bulk and
wall reactions are included.

[JUNCTIONS]
;ID                 Elev            Demand          Pattern  
 10                 710             0                               ;
 11                 710             150                             ;
 12                 700             150                             ;
 13                 695             100                             ;
 21                 700             150                             ;
 22                 695             200                             ;
 23                 690             150                             ;
 31                 700             100                             ;
 32                 710             100                             ;

[RESERVOIRS]
;ID                 Head            Pattern  
 9                  800                             ;

[TANKS]
;ID                 Elevation       InitLevel   MinLevel        MaxLevel        Diameter        MinVol          VolCurve
 2                  850             120             100             150             50.5            0                           ;

[PIPES]
;ID                 Node1               Node2               Length          Diameter        Roughness       MinorLoss       Status
 112                12                  22                  5280            12              100             0               OPEN  ;
 113                13                  23                  5280            8               100             0               OPEN  ;
 21                 21                  22                  5280            10              100             0               OPEN  ;
 122                22                  32                  5280            6               100             0               OPEN  ;
 121                21                  31                  5280            8               100             0               OPEN  ;
 22                 22                  23                  5280            12              100             0               OPEN  ;
 10                 10                  11                  10530           18              100             0               OPEN  ;
 31                 31                  32                  5280            6               100             0               OPEN  ;
 12                 12                  13                  5280            10              100             0               OPEN  ;
 111                11                  21                  5280            10              100             0               OPEN  ;
 110                2                   12                  200             18              100             0               OPEN  ;
 11                 11                  12                  5280            14              100             0               OPEN  ;

[PUMPS]
;ID                 Node1               Node2               Parameters
 9                  9                   10                      HEAD 1         ;

[VALVES]
;ID                 Node1               Node2               Diameter        Type    Setting         MinorLoss 

[DEMANDS]
;Junction           Demand          Pattern             Category

[QUALITY]
;Node               InitQual
23              0.5  
21              0.5  
32              0.5  
2               1.0  
22              0.5  
10              0.5  
13              0.5  
12              0.5  
31              0.5  
9               1.0  
11              0.5         

[SOURCES]
;Node               Type            Quality         Pattern

[PATTERNS]
;ID                 Multipliers
 1                  1               1.2             1.4             1.6             1.4             1.2  
 1                  1               0.8             0.6             0.4             0.6             0.8         

[CURVES]
;ID                 X-Value         Y-Value
 1                  1500                250             

[COORDINATES]
;Node     X-Coord      Y-Coord
23              70              40  
21              30              40  
32              50              10  
2               50              90  
22              50              40  
10              20              70  
13              70              70  
12              50              70  
31              30              10  
9               10              70  
11              30              70          

[VERTICES]
;Linke     X-Coord      Y-Coord

[LABELS]
;X-Coord           Y-Coord          Label & Anchor Node
6.99            73.63           "Source"  
13.48           68.13           "Pump"  
43.85           91.21           "Tank"      

[REACTIONS]
;Type       Pipe/Tank           Coefficient

[REACTIONS]
ORDER BULK              1
ORDER TANK              1
ORDER WALL              1
GLOBAL BULK             -.5
GLOBAL WALL             -1
LIMITING POTENTIAL      0.0
ROUGHNESS CORRELATION   0.0

[LEAKAGE]
;Pipe ID        Leakage Coefficient1        Leakage Coefficient2
113             9.136           0.5  
[STATUS]

[CONTROLS]
LINK 9 OPEN IF NODE 2 BELOW 110
LINK 9 CLOSED IF NODE 2 ABOVE 140

[RULES]

[OPTIONS]
FLOW_UNITS      GPM
HEADLOSS_MODEL      H-W
SPECIFIC_VISCOSITY      1.0
SPECIFIC_DIFFUSIVITY        1.0
SPECIFIC_GRAVITY        1.0
MAXIMUM_TRIALS      40
RELATIVE_ACCURACY       0.001
IF_UNBALANCED       CONTINUE
DEMAND_PATTERN      1
DEMAND_MULTIPLIER       1.0
EMITTER_EXPONENT        0.5
QUALITY_TOLERANCE       0.01
DEMAND_MODEL        FIXED
LEAKAGE_MODEL       POWER
HYDRAULIC_SOLVER        GGA
MATRIX_SOLVER       SPARSPAK
QUALITY_MODEL       CHLORINE
QUALITY_UNITS       MG/L

[TIMES]
DURATION                24:00
HYDRAULIC TIMESTEP      1:00
QUALITY TIMESTEP        0:05
PATTERN TIMESTEP        2:00
PATTERN START           0:00
REPORT TIMESTEP         1:00
REPORT START            0:00
START CLOCKTIME         12 am
STATISTIC               None

[ENERGY]
Global Efficiency   75
Global Price        0.0
Demand Charge       0.0

[EMITTERS]
;Junction    Coefficient    [Exponent]    [Pattern]

[MIXING]
;Tank               Model

[REPORT]
Status              Yes
Summary             No
Page                0

[BACKDROP]
DIMENSIONS      7.00                6.00                73.00               94.00
UNITS           None
FILE
OFFSET          0.00                0.00

[TAGS]
[END]

**Comment by LRossman** [comment]
There was another units conversion bug, this time in the leakage model routine. I have fixed it and published it in the dev3 branch.

**Comment by imksc** [comment]
I download in the dev3 branch. 
I runded
it have emmiter units conversion bug.

and same test

LEAKAGE_MODEL POWER
pipe id 113
LEAKAGE_COEFF1 = 9.136
LEAKAGE_COEFF2 = 0.5

result is 520.80

pipe id = 113 leakage 520.80
start node id = 13    emmiter flow 99.32
end node id = 23    emmiter flow  100.16

I known when same coeff, exponent,
       pipe 113 leakage  ≒  junc 13 emmiter flow  + junc 23 emmiter flow
I think leakage is  approximately  400??

**Comment by LRossman** [comment]
I believe that 520.80 gpm is correct. The output of your example shows that the pressures at the end nodes of the leakage Pipe 113 are 115.489 psi at Node 13 and 117.637 psi at Node 23. The average pressure in the pipe is therefore 116.563. The leakage rate in Pipe 113 is computed from:

`Q = C1 * P^C2 * L / 1000.0`

where C1 is 9.136 per 1000 ft of pipe, C2 is 0.5, P is the average pipe pressure of 116.563 psi and L is the pipe length of 5280 ft. Thus the result for leakage Q is 520.80 gpm. Half of this flow, 260.4 gpm, is assigned as outflow to each of the pipe's end nodes. The output report shows that the total outflow for Node 13 is 360.4 and it's demand is 100, so the difference is 260.4 which is its share of the Pipe 113's leakage. A similar result holds for Node 23.

**Comment by imksc** [comment]
thank you very much for explication.
I mistake to consider the length.
now I understand.
