### ISSUE TITLE
how to use TRACE on quality

### ISSUE THREAD

**Issue by milad-ghiami** [OpenWaterAnalytics/epanet-dev#33]
how to use TRACE on quality

**Comment by LRossman** [comment]
The cause of the error is probably in the optionparser.cpp file where the older EPANET 2 input file syntax is parsed into tokens that EPANET 3 can understand. In the mean time, you should be able to run NET3 if you manually remove the `Quality Trace Lake` line in the INP file and replace it with the new syntax for Quality Options:
```QUALITY_MODEL TRACE```
```TRACE_NODE Lake```

**Comment by milad-ghiami** [comment]
tanx @LRossman  very goode :)
