### ISSUE TITLE
Use of Help File and F1 key in Windows 10

### ISSUE THREAD

**Issue by ArnieStrasser** [OpenWaterAnalytics/epanet-dev#35]
Currently, EPANET 2.00.12 help files cannot be accessed when running under Windows 10. There are temporary workarounds that are short lived when a new Windows 10 updated is installed. A permanent fix would make EPANET more user friendly.

**Comment by eladsal** [comment]
Yes, you have to run the fix again after the Windows 10 update.

**Comment by ArnieStrasser** [comment]
Thanks for your comment. Since I'm new to GitHub, do I simply wait for someone to take on this issue or do I need to create a pull request? I am not a programmer but willing to learn, I've got Delphi 10.2 32 bit version. Will that work on the source code or do I also need C++? Thanks for your help.

**Comment by LRossman** [comment]
@ArnieStrasser this repo is only for development of a next version of EPANET's computational engine, not the graphical user interface. Your issue/question was probably more suitable for the Open Water Analytics EPANET [Community Forum](http://community.wateranalytics.org/). As far as I know, there is currently no open source project devoted to fixing or enhancing the legacy Delphi EPANET GUI, just the new effort to develop a PyQt user interface which you can find [here](https://github.com/USEPA/SWMM-EPANET_User_Interface).

**Comment by ArnieStrasser** [comment]
Thanks for your guidance Lew. I will close this issue and move on the Community Forum.
