### ISSUE TITLE
Can we use TCHAR instead of char to support Unicode?

### ISSUE THREAD

**Issue by softempire** [OpenWaterAnalytics/epanet-dev#44]
Can we use TCHAR instead of char to support Unicode?

**Comment by LRossman** [comment]
Very good suggestion. Instead of TCHAR, which is specific to Visual C++, shouldn't we use `wchar_t` for characters and `wstring` for strings to make the code portable.

**Comment by softempire** [comment]
Also, I think we should extract the strings into a separate resource dll to support globalization/localization
